# Install script for directory: C:/dev/ttt/The-Modern-Cpp-Challenge

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/cppchallenger")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/ZipLib/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/PDF-Writer/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/PNGWriter/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/cryptopp/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/curl/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/libs/curlcpp/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_01/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_02/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_03/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_04/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_05/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_06/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_07/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_08/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_09/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_10/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_11/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_12/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_13/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter01/problem_14/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_15/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_16/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_17/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_18/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_19/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_20/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_21/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter02/problem_22/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_23/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_24/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_25/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_26/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_27/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_28/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_29/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_30/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter03/problem_31/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_32/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_33/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_34/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_35/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_36/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_37/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter04/problem_38/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_39/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_40/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_41/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_42/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_43/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter05/problem_44/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_45/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_46/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_47/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_48/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_49/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_50/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_51/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_52/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_53/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_54/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_55/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_56/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_57/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_58/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_59/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter06/problem_60/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_61/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_62/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_63/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_64/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_65/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter07/problem_66/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_67/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_68/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_69/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_70/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_71/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter08/problem_72/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_73/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_74/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_75/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_76/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_77/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter09/problem_78/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_79/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_80/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_81/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_82/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_83/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_84/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_85/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_86/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter10/problem_87/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_88/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_89/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_90/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_91/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_92/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_93/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter11/problem_94/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_95/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_96c/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_96s/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_97/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_98/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_99/cmake_install.cmake")
  include("C:/dev/ttt/The-Modern-Cpp-Challenge/Chapter12/problem_9a/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/dev/ttt/The-Modern-Cpp-Challenge/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
